# Generated by Django 3.2.12 on 2022-05-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220523_0335'),
        ('movies', '0004_moviecount'),
    ]

    operations = [
    ]
