# Generated by Django 3.2.12 on 2022-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_merge_0004_auto_20220523_0335_0004_moviecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='netflix_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watcha_path',
            field=models.TextField(null=True),
        ),
    ]
