# Generated by Django 3.2.12 on 2022-05-24 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('choice_a', models.CharField(max_length=100)),
                ('choice_b', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('choice_a_users', models.ManyToManyField(related_name='choice_a', to=settings.AUTH_USER_MODEL)),
                ('choice_b_users', models.ManyToManyField(related_name='choice_b', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discusses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss_comments', to='discuss.discuss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
