# Generated by Django 3.2.12 on 2022-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
